[params]
    # ä¹‹å‰çš„ä¸»é¡µç®€ä»‹æˆ‘ä»¬æŠŠå®ƒå…³æ‰ï¼Œæˆ–è€…ç²¾ç®€
    displayStats = true

[[menu.main]]
    name = "ğŸ  é¦–é¡µ"
    url = "/"
    weight = 10
[[menu.main]]
    name = "ğŸ“¹ è§†é¢‘æ›´æ–°"
    url = "/posts"
    weight = 20
[[menu.main]]
    name = "ğŸ“‚ å†…å®¹å½’æ¡£"
    url = "/archives"
    weight = 30
[[menu.main]]
    name = "â˜• å…³äºè±†æµ†"
    url = "/about"
    weight = 40
[[menu.main]]
    name = "ç™»å½•"
    url = "/login"
    weight = 100
[[menu.main]]
    name = "æ³¨å†Œ"
    url = "/register"
    weight = 110